name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: DarekRepos/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.stackoverflow.svg
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 7697951
          plugin_stackoverflow_sections: answers-top, questions-top
          plugin_stackoverflow_limit: 2
