name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
        #set metrics with plugin 
      - uses: DarekRepos/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.stackoverflow.svg
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 7697951
          plugin_stackoverflow_sections: answers-top, questions-top
          plugin_stackoverflow_limit: 2
          
        # set language plugin 
      - uses: DarekRepos/metrics@master
        with:
         filename: metrics.plugin.languages.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_languages: yes
         plugin_languages_ignored: >-
           html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
         plugin_languages_limit: 4
